(function(root){
'use strict';
const base=typeof module!=='undefined'&&module.exports?require('./calculators.js'):root.ErnziCalc;
const fmt=n=>Number(n).toLocaleString('zh-CN',{maximumFractionDigits:6});
const cash=n=>'¥'+Number(n).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});
function num(x,label,min=0,max=1e9){if(String(x).trim()===''||!Number.isFinite(Number(x))||Number(x)<min||Number(x)>max)throw Error(label+'应在 '+min+' 至 '+max+' 之间。');return Number(x);}
function integer(x,label,min,max){const n=num(x,label,min,max);if(!Number.isInteger(n))throw Error(label+'必须是整数。');return n;}
function cents(x){const s=String(x).trim();if(!/^\d+(\.\d{1,2})?$/.test(s))throw Error('金额请使用非负数字，最多两位小数。');return Math.round(num(s,'金额',0,1e7)*100);}
function day(s){base.dateDiff(s,s,false);const [y,m,d]=s.split('-').map(Number);const t=new Date(0);t.setUTCFullYear(y,m-1,d);t.setUTCHours(0,0,0,0);return t;}
function iso(y,m,d){return String(y).padStart(4,'0')+'-'+String(m).padStart(2,'0')+'-'+String(d).padStart(2,'0');}
const bands=[[36000,.03,0],[144000,.1,2520],[300000,.2,16920],[420000,.25,31920],[660000,.30,52920],[960000,.35,85920],[Infinity,.45,181920]];
function tax(taxable){const b=bands.find(b=>taxable<=b[0]);return Math.round(Math.max(0,taxable*b[1]-b[2])*100)/100;}
function quote(price,a,b,coupon,shipping,order){const p=cents(price),c=cents(coupon),ship=cents(shipping);num(a,'第一次折扣',0,10);num(b,'第二次折扣',0,10);const x=cents(a),y=cents(b);return (order==='before'?Math.round(Math.max(0,p-c)*x*y/1000000):Math.max(0,Math.round(p*x*y/1000000)-c))+ship;}
const units={length:{mm:['毫米',.001],cm:['厘米',.01],m:['米',1],km:['千米',1000],in:['英寸',.0254],ft:['英尺',.3048],yd:['码',.9144],mi:['英里',1609.344],li:['市里',500]},mass:{g:['克',1],mg:['毫克',.001],kg:['千克',1000],t:['吨',1e6],lb:['常衡磅',453.59237],oz:['常衡盎司',28.349523125],jin:['市斤',500]},area:{m2:['平方米',1],cm2:['平方厘米',.0001],km2:['平方千米',1e6],ha:['公顷',10000],mu:['市亩',2000/3],ft2:['平方英尺',.09290304],acre:['英亩',4046.8564224]},volume:{ml:['毫升',.001],l:['升',1],m3:['立方米',1000],gal:['美制液量加仑',3.785411784],ukgal:['英制加仑',4.54609]},speed:{ms:['米/秒',1],kmh:['千米/小时',1/3.6],mph:['英里/小时',.44704],kn:['节',1852/3600]},temperature:{c:['摄氏度'],f:['华氏度'],k:['开尔文']}};
function convert(value,cat,from,to){const u=units[cat];if(!u||!u[from]||!u[to])throw Error('请选择同一类别中的单位。');const v=num(value,'数值',cat==='temperature'?-1e12:0,1e12);if(cat!=='temperature')return v*u[from][1]/u[to][1];let c=from==='c'?v:from==='f'?(v-32)*5/9:v-273.15;if(c< -273.150000001)throw Error('温度不能低于绝对零度。');return to==='c'?c:to==='f'?c*9/5+32:c+273.15;}
function randomInt(min,max,rng){const range=max-min+1,cap=Math.floor(4294967296/range)*range;let n;do{n=rng();}while(n>=cap);return min+n%range;}
function evaluate(kind,v,rng){
const n=(key,label,min,max)=>num(v[key],label,min,max), i=(key,label,min,max)=>integer(v[key],label,min,max);
let headline='',lines=[],headers=[],rows=[];
switch(kind){
case 'date-diff':{const r=base.dateDiff(v.start,v.end,v.inclusive);headline=r.days+' 天';lines=[r.weeks+' 周 '+r.remainder+' 天',v.inclusive?'起止两天均计数；同一天计 1 天。':'日期间隔；同一天计 0 天。','所有周末与节假日均计入。'];break;}
case 'countdown':{const d=(day(v.target)-day(v.reference))/864e5;headline=d===0?'就是当天':d>0?'还有 '+d+' 天':'已过去 '+(-d)+' 天';lines=['参照日期：'+v.reference+'；目标日期：'+v.target,'按自然日期计算，不使用近似月份，也不扣除节假日。'];break;}
case 'age':{const b=day(v.birth),r=day(v.reference);if(b>r)throw Error('出生日期不能晚于参照日期。');const y=r.getUTCFullYear(),m=b.getUTCMonth()+1,d=b.getUTCDate();let anniversary;
try{anniversary=day(iso(y,m,d));}catch(e){anniversary=day(iso(y,3,1));}
const age=y-b.getUTCFullYear()-(r<anniversary?1:0);let next=anniversary;
if(next<r){try{next=day(iso(y+1,m,d));}catch(e){next=day(iso(y+1,3,1));}}
headline=age+' 周岁';lines=['从出生日期起相隔 '+((r-b)/864e5)+' 天','距下一个生日 '+((next-r)/864e5)+' 天','本工具将非闰年的 2 月 29 日生日按 3 月 1 日计算；不用于认定法定年龄或退休日期。'];break;}
case 'discount':{const a=quote(v.price,v.first,v.second,v.coupon,v.shipping,v.order),b=quote(v.price,v.altFirst,v.altSecond,v.altCoupon,v.altShipping,v.altOrder);headline=a===b?'两方案实付相同':(a<b?'方案 A':'方案 B')+' 少付 '+cash(Math.abs(a-b)/100);headers=['方案','含运费实付','相对原价差额（含运费）'];const p=cents(v.price);rows=[['A',cash(a/100),cash((p-a)/100)],['B',cash(b/100),cash((p-b)/100)]];lines=['已按所选顺序处理立减与折扣；金额最低为 0 后再加运费。','不自动判断优惠券门槛、商品参与资格或平台补贴。'];break;}
case 'tip':{const count=i('people','人数',1,50);const w=v.mode==='equal'?Array(count).fill('1'):v.weights;const r=base.split(v.total,v.tip,w);headline='总账单 '+cash(r.total/100);headers=['人员','应付份额'];rows=r.shares.map((s,j)=>['第 '+(j+1)+' 人',cash(s/100)]);lines=['其中小费/服务费 '+cash(r.tip/100)+'；分摊金额合计与总账单一致。'];
if(v.settle){if(!Array.isArray(v.paid)||v.paid.length!==count)throw Error('请填写每个人已付金额。');const paid=v.paid.map(cents);if(paid.reduce((a,b)=>a+b,0)!==r.total)throw Error('已付金额合计必须等于含小费的总账单 '+cash(r.total/100)+'，才能计算转账。');const owe=[],get=[];paid.forEach((p,j)=>{const d=p-r.shares[j];if(d<0)owe.push({j,n:-d});if(d>0)get.push({j,n:d});});let a=0,b=0;while(a<owe.length&&b<get.length){const c=Math.min(owe[a].n,get[b].n);lines.push('第 '+(owe[a].j+1)+' 人 → 第 '+(get[b].j+1)+' 人：'+cash(c/100));owe[a].n-=c;get[b].n-=c;if(!owe[a].n)a++;if(!get[b].n)b++;}if(!owe.length)lines.push('每个人均已付清自己的份额，无需转账。');}break;}
case 'mortgage':{const p=n('principal','本金',.01,1e8),months=i('months','期数',1,600),rate=n('rate','年利率',0,30)/1200;let balance=p,total=0,interest=0;const payment=rate===0?p/months:p*rate/(-Math.expm1(-months*Math.log1p(rate)));
headers=['期数','还款额（元）','本金（元）','利息（元）','剩余本金（元）'];for(let j=1;j<=months;j++){const it=balance*rate,pr=j===months?balance:v.method==='principal'?p/months:payment-it;balance=Math.max(0,balance-pr);total+=pr+it;interest+=it;rows.push([j,(pr+it).toFixed(2),pr.toFixed(2),it.toFixed(2),balance.toFixed(2)]);}headline='利息合计 '+cash(interest);lines=['还款总额 '+cash(total),'首期 '+cash(Number(rows[0][1]))+'；末期 '+cash(Number(rows.at(-1)[1])),'固定利率数学估算，内部不逐期舍入；银行逐期计息及尾期处理可能不同。'];break;}
case 'interest':{const p=n('principal','本金',0,1e8),rate=n('rate','年利率',0,100)/100,years=n('years','年数',0,100),frequency=i('frequency','年复利次数',1,365);const simple=p*(1+rate*years),compound=p*Math.pow(1+rate/frequency,frequency*years);if(compound>1e15)throw Error('结果过大，请缩短期限或降低利率。');headline='复利本息 '+cash(compound);headers=['模型','利息','本息合计'];rows=[['单利',cash(simple-p),cash(simple)],['复利',cash(compound-p),cash(compound)]];lines=['复利比单利多 '+cash(compound-simple),'假设利率固定、收益再投入，不含追加投入、费用或税款。'];break;}
case 'tax':{const income=cents(v.income)/100,deduct=cents(v.deduct)/100,prepaid=cents(v.prepaid)/100;const taxable=Math.max(0,income-60000-deduct),due=tax(taxable),difference=Math.round((due-prepaid)*100)/100;headline='年度税额估算 '+cash(due);lines=['应纳税所得额 '+cash(taxable),difference>0?'与已预缴相比还差 '+cash(difference):'与已预缴相比多缴 '+cash(-difference),'按已换算好的综合所得收入额计算，不直接把所有收入流水当作收入额。'];headers=['应纳税所得额上限','税率','速算扣除数'];rows=bands.map(b=>[b[0]===Infinity?'超过 960,000 元':fmt(b[0])+' 元',b[1]*100+'%',fmt(b[2])+' 元']);break;}
case 'salary':{const monthly=cents(v.salary)/100,insurance=cents(v.insurance)/100,deduction=cents(v.deduction)/100;if(insurance>monthly)throw Error('个人社保与公积金不能大于月工资。');let last=0,total=0;headers=['月份','累计计税所得额','当月预扣税估算','当月到手估算'];for(let m=1;m<=12;m++){const taxable=Math.max(0,(monthly-insurance-deduction-5000)*m),due=tax(taxable),current=Math.round((due-last)*100)/100;last=due;const net=monthly-insurance-current;total+=net;rows.push([m,cash(taxable),cash(current),cash(net)]);}headline='全年到手估算 '+cash(total);lines=['全年预扣税估算 '+cash(last),'假设从 1 月起在同一单位连续领取 12 个月相同工资和扣除。','专项附加扣除用于减少计税所得，不会从工资再次扣走。'];break;}
case 'bmi':{const h=n('height','身高（厘米）',50,250)/100,w=n('weight','体重（千克）',10,400),b=w/(h*h);headline='BMI '+b.toFixed(2);const label=b<18.5?'低于 18.5':b<25?'18.5 至小于 25':b<30?'25 至小于 30':'30 及以上';lines=['WHO 成人分组：'+label,'按未舍入数值判断分组。仅适用于成人的一般筛查，不用于儿童、孕期或个人疾病诊断。'];break;}
case 'power':{const w=n('watts','运行功率',0,1e6),h=n('hours','每天运行小时',0,24),s=n('standby','待机功率',0,1e6),days=i('days','天数',1,366),price=n('price','电价',0,100);const active=w*h*days/1000,idle=s*(24-h)*days/1000;headline='预计电费 '+cash((active+idle)*price);lines=['运行用电 '+fmt(active)+' kWh','待机用电 '+fmt(idle)+' kWh','合计 '+fmt(active+idle)+' 度电；估算期 '+days+' 天'];break;}
case 'percentage':{const a=n('a','数值 A',-1e12,1e12),b=n('b','数值 B',-1e12,1e12);if(v.mode==='part'){headline=fmt(a*b/100);lines=[fmt(a)+' 的 '+fmt(b)+'% = '+fmt(a*b/100)];}else if(v.mode==='ratio'){if(b===0)throw Error('作为总量的 B 不能为 0。');headline=fmt(a/b*100)+'%';lines=['A ÷ B × 100%；注意分母是总量 B。'];}else{if(a<=0)throw Error('增长率模式要求原值 A 大于 0；零或负基数不适合此处的增长率口径。');headline=fmt((b-a)/a*100)+'%';lines=['（新值 B − 原值 A）÷ 原值 A × 100%','绝对变化 '+fmt(b-a)];}break;}
case 'converter':{const radix=i('base','进制',2,16);if(![2,8,10,16].includes(radix))throw Error('进制不支持。');let s=String(v.value).trim();if(s.length>256)throw Error('最多输入 256 个字符。');const negative=s.startsWith('-');if(negative)s=s.slice(1);const pattern={2:/^[01]+$/,8:/^[0-7]+$/,10:/^\d+$/,16:/^[\da-f]+$/i};if(!pattern[radix].test(s))throw Error('输入包含不属于所选进制的字符；请勿加 0x 等前缀或小数点。');let value=0n;for(const ch of s.toLowerCase())value=value*BigInt(radix)+BigInt(parseInt(ch,16));if(negative)value=-value;headline='整数转换完成';headers=['进制','精确结果'];rows=[2,8,10,16].map(b=>[b,value.toString(b).toUpperCase()]);lines=['使用大整数逐位解析，不经浮点数转换；负数显示数学负号，不表示补码。'];break;}
case 'area-calc':{const a=n('a','尺寸 A',.000001,1e6),b=v.shape==='circle'?0:n('b','尺寸 B',.000001,1e6),c=v.shape==='trapezoid'?n('c','尺寸 C',.000001,1e6):0;const area=v.shape==='circle'?Math.PI*a*a:v.shape==='triangle'?a*b/2:v.shape==='trapezoid'?(a+b)*c/2:a*b;headline=fmt(area)+' 平方米';lines=['折合 '+fmt(area*10000)+' 平方厘米','所有输入均按米计算；三角形的高必须垂直于底边。'];break;}
case 'unit':{const r=convert(v.value,v.category,v.from,v.to);headline=fmt(r)+' '+units[v.category][v.to][0];lines=[fmt(Number(v.value))+' '+units[v.category][v.from][0]+' = '+fmt(r)+' '+units[v.category][v.to][0],'页面最多显示 6 位小数；极小结果可能显示为 0，原始数值：'+r.toPrecision(12)];break;}
case 'random':{const a=i('min','最小值',-1e9,1e9),b=i('max','最大值',-1e9,1e9),count=i('count','数量',1,100);if(b<a)throw Error('最大值不能小于最小值。');const size=b-a+1;if(v.unique&&count>size)throw Error('不重复数量不能超过区间内整数个数。');if(!rng)throw Error('浏览器不支持所需的随机数接口。');const result=[];if(v.unique){const map=new Map();let remaining=size;for(let j=0;j<count;j++){const index=randomInt(0,remaining-1,rng);result.push(a+(map.has(index)?map.get(index):index));const tail=remaining-1;map.set(index,map.has(tail)?map.get(tail):tail);map.delete(tail);remaining--;}}else for(let j=0;j<count;j++)result.push(randomInt(a,b,rng));headline=count+' 个随机整数';lines=[result.join('、'),'区间包含两个端点；'+(v.unique?'本次结果不重复。':'允许重复，不同抽取相互独立。')];break;}
default:throw Error('未知工具。');
}return {headline,lines,headers,rows};}
const api={evaluate,units,convert,tax,quote,day,randomInt};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.ReviewCalc=api;
})(typeof globalThis!=='undefined'?globalThis:this);
